PRDSWEB/src/com/rintis/marketing/web/jsf/main/qr/AddWhitelistMPanManagedBean.java
package com.rintis.marketing.web.jsf.main.qr;

import com.rintis.marketing.beans.bean.bi.WhitelistQRBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.web.common.PageConstant;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.util.HashMap;
import java.util.List;

/**
 * Created by aaw on 28/06/21.
 */

@ManagedBean
@ViewScoped
public class AddWhitelistMPanManagedBean extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private WhitelistQRBean whitelistQRBean;
    private List<com.rintis.marketing.beans.bean.report.BankBean> listBankReport;
    private String selectedBankId;

    @Override
    @PostConstruct
    protected void initManagedBean() {
        whitelistQRBean = new WhitelistQRBean();
        try {
            listBankReport = moduleFactory.getMasterService().listBank(new HashMap<>());
        }catch(Exception e){
            log.error(e.getMessage(), e);
        }
    }

    public boolean isAlpha(String acct) {
        boolean res = false;
        for (char c : acct.toCharArray()) {
            if((Character.isLetter(c))) {
                System.out.println("Is a character! " + c);
                res = true;
                break;
            }
        }
        return res;
    }

    public boolean containsDigit(String acct) {
        boolean res = false;
        if (acct != null && !acct.isEmpty()) {
            for (char c :  acct.toCharArray()) {
                if(Character.isDigit(c)) {
                    res = true;
                    break;
                }
            }
        }
        return res;
    }

    public String saveAction() {
        try {
            if (whitelistQRBean.getPan().length() == 0) {
                glowMessageError("Enter PAN", "");
                return "";
            }

            if (isAlpha(whitelistQRBean.getPan().trim()) || !containsDigit(whitelistQRBean.getPan().trim())) {
                glowMessageError("'PAN' Not Valid", "Please Chek PAN Number!");
                return "";
            }

            if (selectedBankId == null || selectedBankId == "") {
                glowMessageError("Acquirer Bank Is Required!", "");
                return "";
            }

            boolean chk = moduleFactory.getMPanTresholdService().checkMPanUsed(whitelistQRBean.getPan().trim(), selectedBankId);
            if (chk) {
                glowMessageError("PAN And Acquirer Bank Already Exist", "");
                return "";
            }

            String act = whitelistQRBean.getActive().toString();

            whitelistQRBean.setPan(whitelistQRBean.getPan().trim());
            whitelistQRBean.setAcquirerId(selectedBankId);
            whitelistQRBean.setFreqApp(whitelistQRBean.getFreqApp());
            whitelistQRBean.setFreqDc(whitelistQRBean.getFreqDc());
            whitelistQRBean.setFreqDcFree(whitelistQRBean.getFreqDcFree());
            whitelistQRBean.setFreqRvsl(whitelistQRBean.getFreqRvsl());
            whitelistQRBean.setTotalAmtApp(whitelistQRBean.getTotalAmtApp());
            whitelistQRBean.setTotalAmtDc(whitelistQRBean.getTotalAmtDc());
            whitelistQRBean.setTotalAmtDcFree(whitelistQRBean.getTotalAmtDcFree());
            whitelistQRBean.setTotalAmtRvsl(whitelistQRBean.getTotalAmtRvsl());
            whitelistQRBean.setTotalAmt(whitelistQRBean.getTotalAmt());
            whitelistQRBean.setActive(act);

            moduleFactory.getMPanTresholdService().saveMPanTreshold(whitelistQRBean);

            if (!isPostback()) {
                createTlog(moduleFactory);
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return PageConstant.PAGE_WHITELIST_MPAN + "?faces-redirect=true";
    }

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public WhitelistQRBean getWhitelistQRBean() {
        return whitelistQRBean;
    }

    public void setWhitelistQRBean(WhitelistQRBean whitelistQRBeann) {
        this.whitelistQRBean = whitelistQRBean;
    }

    public List<com.rintis.marketing.beans.bean.report.BankBean> getListBankReport() {
        return listBankReport;
    }

    public void setListBankReport(List<com.rintis.marketing.beans.bean.report.BankBean> listBankReport) {
        this.listBankReport = listBankReport;
    }

    public String getSelectedBankId() {
        return selectedBankId;
    }

    public void setSelectedBankId(String selectedBankId) {
        this.selectedBankId = selectedBankId;
    }
}

PRDSWEB/src/com/rintis/marketing/web/jsf/main/qr/DetailMPanAnomalyQRManagedBean.java
package com.rintis.marketing.web.jsf.main.qr;

import com.google.common.collect.ComparisonChain;
import com.rintis.marketing.beans.bean.bi.DetailMPanAnomalyBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.core.utils.HttpUtils;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 * Created by aaw on 30/06/2021.
 */

@ManagedBean
@ViewScoped
public class DetailMPanAnomalyQRManagedBean extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private List<DetailMPanAnomalyBean> list;
    private String pPeriod;
    private String pPeriodTo;
    private String pPeriodType;
    private String pTimeFr;
    private String pTimeTo;
    private String pPan;
    private String pAcquirerBank;
    private String pAcquirerId;
    private String pTranType;
    private String pTranTypeId;
    private String pGroupId;
    private String pQrType;
    private int colspan;
    private String totalAmt;
    private String pTermId;
    private String pTermName;

    @Override
    @PostConstruct
    protected void initManagedBean() {

        try {
            pPeriodType = paramEncode(getRequestParameterMap().get("pPeriodType").toString());
            if ("3D".equalsIgnoreCase(pPeriodType)) {
                pPeriod = paramEncode(getRequestParameterMap().get("pPeriodFrom").toString());
            } else {
                pPeriod = paramEncode(getRequestParameterMap().get("pPeriod").toString());
            }
            pPeriodTo = paramEncode(getRequestParameterMap().get("pPeriodTo").toString());
            pTimeFr = paramEncode(getRequestParameterMap().get("pTimeFr").toString().replace(":", ""));
            pTimeTo = paramEncode(getRequestParameterMap().get("pTimeTo").toString().replace(":", ""));
            pPan = paramEncode(getRequestParameterMap().get("pPan").toString());
            pAcquirerId = paramEncode(getRequestParameterMap().get("pAcqId").toString());
            pAcquirerBank = paramEncode(getRequestParameterMap().get("pAcqBank").toString());
            pTranType = "QR";
            pQrType = paramEncode(getRequestParameterMap().get("pQrType").toString());
            pGroupId = moduleFactory.getPanService().getGroupIdFromTrxName(pTranType);
            pTranTypeId = moduleFactory.getPanService().getTrxIdFromTrxName(pTranType);
            pTermId = paramEncode(getRequestParameterMap().get("pTermId").toString());
            pTermName = paramEncode(getRequestParameterMap().get("pTermName").toString());

            if (!isPostback()) {
                createTlog(moduleFactory);
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
    }

    public String submitAction() {
        try {
            List<DetailMPanAnomalyBean> def = new ArrayList<>();
            def = moduleFactory.getQRService().listDetailMPanQR(pPeriod, pTimeFr, pTimeTo, pPan, pQrType, pAcquirerId, pPeriodTo, pPeriodType, pTermId, pTermName);
            if(!def.isEmpty()){
                list = sortingListMpan(def);
            }

            colspan = 9;
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return "";
    }

    public List<DetailMPanAnomalyBean> sortingListMpan (List<DetailMPanAnomalyBean> in) {

        Collections.sort(in, new Comparator<DetailMPanAnomalyBean>() {
            @Override
            public int compare(DetailMPanAnomalyBean o1, DetailMPanAnomalyBean o2) {
                return ComparisonChain.start()
                    .compare(o1.getPeriod(), o2.getPeriod())
                    .compare(o1.getTrxTime(), o2.getTrxTime())
                    .result();
                /*Above is sorting ascending, for descending use :
                .compare(o2.getPeriod(), o1.getPeriod()) */
            }
        });
        System.out.println("Result Sort : " + in);
        return in;
    }

    public String paramEncode(String data){
        if(!data.equals(null)){
            data = HttpUtils.encodeUrlParam(data, getUserInfoBean().getUserId(), getHttpSession().getId());
        }
        return data;
    }

    public String getValueAmtTotal() {
        Double totAmt = 0.00;

        if(list != null){
            for(DetailMPanAnomalyBean l : list) {
                totAmt += Double.parseDouble(l.getAmount().toString());
            }
        }

        DecimalFormat formatter = new DecimalFormat("###,###,###.00");
        totalAmt = formatter.format(totAmt);

        return totalAmt;
    }

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public List<DetailMPanAnomalyBean> getList() {
        return list;
    }

    public void setList(List<DetailMPanAnomalyBean> list) {
        this.list = list;
    }

    public String getpPeriod() {
        return pPeriod;
    }

    public void setpPeriod(String pPeriod) {
        this.pPeriod = pPeriod;
    }

    public String getpTimeFr() {
        return pTimeFr;
    }

    public void setpTimeFr(String pTimeFr) {
        this.pTimeFr = pTimeFr;
    }

    public String getpTimeTo() {
        return pTimeTo;
    }

    public void setpTimeTo(String pTimeTo) {
        this.pTimeTo = pTimeTo;
    }

    public String getpPan() {
        return pPan;
    }

    public void setpPan(String pPan) {
        this.pPan = pPan;
    }

    public String getpTranType() {
        return pTranType;
    }

    public void setpTranType(String pTranType) {
        this.pTranType = pTranType;
    }

    public String getpTranTypeId() {
        return pTranTypeId;
    }

    public void setpTranTypeId(String pTranTypeId) {
        this.pTranTypeId = pTranTypeId;
    }

    public String getpGroupId() {
        return pGroupId;
    }

    public void setpGroupId(String pGroupId) {
        this.pGroupId = pGroupId;
    }

    public int getColspan() {
        return colspan;
    }

    public void setColspan(int colspan) {
        this.colspan = colspan;
    }


    public String getpAcquirerId() {
        return pAcquirerId;
    }

    public void setpAcquirerId(String pAcquirerId) {
        this.pAcquirerId = pAcquirerId;
    }

    public String getpQrType() {
        return pQrType;
    }

    public void setpQrType(String pQrType) {
        this.pQrType = pQrType;
    }

    public String getTotalAmt() {
        return totalAmt;
    }

    public void setTotalAmt(String totalAmt) {
        this.totalAmt = totalAmt;
    }

    public String getpAcquirerBank() {
        return pAcquirerBank;
    }

    public void setpAcquirerBank(String pAcquirerBank) {
        this.pAcquirerBank = pAcquirerBank;
    }

    public String getpPeriodTo() {
        return pPeriodTo;
    }

    public void setpPeriodTo(String pPeriodTo) {
        this.pPeriodTo = pPeriodTo;
    }

    public String getpPeriodType() {
        return pPeriodType;
    }

    public void setpPeriodType(String pPeriodType) {
        this.pPeriodType = pPeriodType;
    }

    public String getpTermId() {
        return pTermId;
    }

    public void setpTermId(String pTermId) {
        this.pTermId = pTermId;
    }

    public String getpTermName() {
        return pTermName;
    }

    public void setpTermName(String pTermName) {
        this.pTermName = pTermName;
    }
}

PRDSWEB/src/com/rintis/marketing/web/jsf/main/qr/EditWhitelistMPanManagedBean.java
package com.rintis.marketing.web.jsf.main.qr;

import com.rintis.marketing.beans.bean.bi.WhitelistQRBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.web.common.PageConstant;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.math.BigDecimal;
import java.util.List;

/**
 * Created by aaw on 28/06/2021.
 */

@ManagedBean
@ViewScoped
public class EditWhitelistMPanManagedBean extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private List<WhitelistQRBean> listWhitelistMPan;

    @Override
    @PostConstruct
    protected void initManagedBean() {
        String pan = (String)getRequestParameterMap().get("wlPan");
        String acquirerId = (String)getRequestParameterMap().get("wlAcqId");

        if (pan != null && pan.trim() != "") {
            try {
                listWhitelistMPan = moduleFactory.getMPanTresholdService().getWhitelistMPan(pan.trim(), acquirerId);
                if (!isPostback()) {
                    createTlog(moduleFactory);
                }
            } catch (Exception e) {
                log.error(e.getMessage(), e);
            }
        }
    }

    public String editAction() {
        try {
            if (listWhitelistMPan.get(0).getPan().length() == 0) {
                glowMessageError("Data Not Valid, 'PAN' Is Blank!", "");
                return "";
            }
            String mpan = listWhitelistMPan.get(0).getPan().trim();
            String acqId = listWhitelistMPan.get(0).getAcquirerId();
            BigDecimal freqApp = listWhitelistMPan.get(0).getFreqApp();
            BigDecimal freqDc = listWhitelistMPan.get(0).getFreqDc();
            BigDecimal freqDcFree = listWhitelistMPan.get(0).getFreqDcFree();
            BigDecimal freqRvsl = listWhitelistMPan.get(0).getFreqRvsl();
            BigDecimal totalAmtApp = listWhitelistMPan.get(0).getTotalAmtApp();
            BigDecimal totalAmtDc = listWhitelistMPan.get(0).getTotalAmtDc();
            BigDecimal totalAmtDcFree = listWhitelistMPan.get(0).getTotalAmtDcFree();
            BigDecimal totalAmtRvsl = listWhitelistMPan.get(0).getTotalAmtRvsl();
            BigDecimal totalAmt = listWhitelistMPan.get(0).getTotalAmt();
            String active = listWhitelistMPan.get(0).getActive();

            moduleFactory.getMPanTresholdService().updateMPan(mpan, acqId, freqApp, freqDc, freqDcFree, freqRvsl, totalAmtApp, totalAmtDc, totalAmtDcFree, totalAmtRvsl, totalAmt, active);

            if (!isPostback()) {
                createTlog(moduleFactory);
            }

        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return PageConstant.PAGE_WHITELIST_MPAN + "?faces-redirect=true";
    }

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public List<WhitelistQRBean> getListWhitelistMPan() {
        return listWhitelistMPan;
    }

    public void setListWhitelistMPan(List<WhitelistQRBean> listWhitelistMPan) {
        this.listWhitelistMPan = listWhitelistMPan;
    }
}

PRDSWEB/web/apps/qr/detailMPanAnomalyQR.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
                template="../common/template/private_template.xhtml">
    <!--This Page created by aaw, 30 June 2021-->
    <ui:define name="content">

        <p:panel header="Detail Acquirer QR (MPAN) Anomaly" styleClass="panelContent">
            <h:form id="frm1" >
                <p:growl id="growl" showDetail="true" sticky="true" life="2000" />

                <div class="divPanelForm">
                    <table>
                        <tr>
                            <td>
                                <h:panelGrid columnClasses="panelGridFirstColumn, panelGridSecondColumn" columns="2" border="0" cellpadding="2" cellspacing="0">
                                    <h:outputText styleClass="bold" value="Acquirer Bank : " />
                                    <h:outputText value="#{detailMPanAnomalyQRManagedBean.pAcquirerBank}" />

                                    <h:outputText styleClass="bold" value="Merchant PAN : " />
                                    <c:set var = "bin" value="#{(detailMPanAnomalyQRManagedBean.pPan.trim()).substring(0,6)}"/>
                                    <c:set var = "filler" value="#{(detailMPanAnomalyQRManagedBean.pPan.trim()).substring(6,(detailMPanAnomalyQRManagedBean.pPan.trim()).length()-4)}"/>
                                    <c:set var = "fillerAsterisks" value="${fn:replace(filler, '[0-9]', '*')}"/>
                                    <c:set var = "suffix" value="#{(detailMPanAnomalyQRManagedBean.pPan.trim()).substring((detailMPanAnomalyQRManagedBean.pPan.trim()).length()-4,(detailMPanAnomalyQRManagedBean.pPan.trim()).length())}"/>
                                    <h:outputText value="#{bin.concat(fillerAsterisks).concat(suffix)}" />

                                    <h:outputText styleClass="bold" value="Term ID : " />
                                    <h:outputText value="#{detailMPanAnomalyQRManagedBean.pTermId}" />
                                    <h:outputText styleClass="bold" value="Term Name : " />
                                    <h:outputText value="#{detailMPanAnomalyQRManagedBean.pTermName}" />
                                    <ui:remove>
                                    <h:outputText value="#{detailMPanAnomalyQRManagedBean.pPan}" />


                                    <h:outputText styleClass="bold" value="Receiver : " />
                                    <h:outputText value="" />
                                    </ui:remove>
                                    <br/>

                                    <h:outputLabel />
                                    <p:commandButton value="View Detail" action="#{detailMPanAnomalyQRManagedBean.submitAction}" onbegin="PF('pleaseWaitDialog').show()" oncomplete="PF('pleaseWaitDialog').hide()" update="frm1" />

                                </h:panelGrid>
                            </td>
                        </tr>
                    </table>

                    <p:separator />

                    <p:dataTable id="idTable" var="item" rowIndexVar="idx" value="#{detailMPanAnomalyQRManagedBean.list}"
                                 rows="20" paginator="true" paginatorAlwaysVisible="true" paginatorPosition="bottom"
                                 style="width:100%; font-size:11px;">

                        <p:columnGroup type="header">
                            <p:row style="font-size:12px;">
                                <p:column rowspan="3" headerText="#{msg.no}" />
                                <p:column rowspan="3" headerText="Date" sortBy="#{item.period}" />
                                <p:column rowspan="3" headerText="Time" sortBy="#{item.trxTime}" />
                                <p:column rowspan="3" headerText="Card No" sortBy="#{item.cardNo}" filterBy="${item.cardNo}" filterMatchMode="contains" />
                                <p:column rowspan="3" headerText="Issuer Bank" sortBy="#{item.issuerBank}" filterBy="${item.issuerBank}" filterMatchMode="contains" />

                                <ui:remove>
                                <p:column rowspan="3" headerText="Merchant PAN" sortBy="#{item.pan}" />
                                <p:column rowspan="3" headerText="Issuer Bank" sortBy="#{item.issuerBank}" />
                                </ui:remove>

                                <ui:remove>
                                <p:column rowspan="3" headerText="Term Owner Name" sortBy="#{item.terminal}" />
                                <p:column rowspan="3" headerText="Term-ID" sortBy="#{item.termId}" />
                                </ui:remove>
                                <p:column colspan="4" headerText="Details" />

                                <ui:remove>
                                <p:column colspan="4" headerText="Frequency" />
                                </ui:remove>

                                <p:column rowspan="3" headerText="Amount" sortBy="#{item.amount}" />
                            </p:row>
                            <p:row style="font-size:12px;">
                                <p:column headerText="Msg Type" sortBy="#{item.msgtype}" />
                                <p:column headerText="POS Entry Mode" sortBy="#{item.posentrymode}" />
                                <p:column headerText="Response Code" sortBy="#{item.rc}" />
                                <p:column headerText="Description" sortBy="#{item.description}" />

                                <ui:remove>
                                <p:column rowspan="2" headerText="#{msg.approve}" sortBy="#{item.app}" />
                                <p:column colspan="2" headerText="#{msg.decline}" />
                                <p:column rowspan="2" headerText="Refund" sortBy="#{item.rvsl}" />
                                </ui:remove>
                            </p:row>

                            <ui:remove>
                            <p:row style="font-size:12px;">
                                <p:column headerText="Charge" sortBy="#{item.dc}" />
                                <p:column headerText="Free" sortBy="#{item.dcFree}" />
                            </p:row>
                            </ui:remove>
                        </p:columnGroup>

                        <p:column style="width:10px" >
                            <h:outputText value="#{idx+1}" />
                        </p:column>

                        <p:column style="width:70px">
                            <h:outputText value="#{item.period}" />
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.trxTime}" />
                        </p:column>

                        <p:column >
                            <c:set var = "bin" value="#{(item.cardNo.trim()).substring(0,6)}"/>
                            <c:set var = "filler" value="#{(item.cardNo.trim()).substring(6,(item.cardNo.trim()).length()-4)}"/>
                            <c:set var = "fillerAsterisks" value="${fn:replace(filler, '[0-9]', '*')}"/>
                            <c:set var = "suffix" value="#{(item.cardNo.trim()).substring((item.cardNo.trim()).length()-4,(item.cardNo.trim()).length())}"/>
                            <h:outputText value="#{bin.concat(fillerAsterisks).concat(suffix)}" />
                            <ui:remove>
                            <h:outputText value="#{item.cardNo}" />
                            </ui:remove>
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.issuerBank}" />
                        </p:column>

                        <ui:remove>
                        <p:column >
                            <c:set var = "bin" value="#{(item.pan.trim()).substring(0,6)}"/>
                            <c:set var = "filler" value="#{(item.pan.trim()).substring(6,(item.pan.trim()).length()-4)}"/>
                            <c:set var = "fillerAsterisks" value="${fn:replace(filler, '[0-9]', '*')}"/>
                            <c:set var = "suffix" value="#{(item.pan.trim()).substring((item.pan.trim()).length()-4,(item.pan.trim()).length())}"/>
                            <h:outputText value="#{bin.concat(fillerAsterisks).concat(suffix)}" />
                            <ui:remove>
                            <h:outputText value="#{item.pan}" />
                            </ui:remove>
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.bankacq}" />
                        </p:column>
                        </ui:remove>

                        <ui:remove>
                        <p:column >
                            <h:outputText value="#{item.terminal}" />
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.termId}" />
                        </p:column>
                        </ui:remove>
                        <!--<p:column rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}">-->
                           <!-- <h:outputText rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}" value="#{item.bankBene}" />-->
                        <!--</p:column>-->

                        <!--<p:column rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}">-->
                            <!--<h:outputText rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}" value="#{item.nameBene}" />-->
                        <!--</p:column>-->

                        <!--<p:column rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}">-->
                            <!--<h:outputText rendered="#{detailMPanAnomalyQRManagedBean.beneficiary}" value="#{item.toAccount}" />-->
                        <!--</p:column>-->

                        <p:column >
                            <h:outputText value="#{item.msgtype}" />
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.posentrymode}" />
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.rc}" />
                        </p:column>

                        <p:column >
                            <h:outputText value="#{item.description}" />
                        </p:column>

                        <ui:remove>
                        <p:column >
                            <div align="right" >
                                <h:outputText value="#{item.app}" />
                            </div>
                        </p:column>

                        <p:column >
                            <div align="right" >
                                <h:outputText value="#{item.dc}" />
                            </div>
                        </p:column>

                        <p:column >
                            <div align="right" >
                                <h:outputText value="#{item.dcFree}" />
                            </div>
                        </p:column>

                        <p:column >
                            <div align="right" >
                                <h:outputText value="#{item.rvsl}" />
                            </div>
                        </p:column>
                        </ui:remove>

                        <p:column >
                            <div align="right">
                                <h:outputText value="#{item.amount}">
                                    <f:convertNumber groupingUsed="true" minFractionDigits="2" />
                                </h:outputText>
                            </div>
                        </p:column>

                        <p:columnGroup type="footer" style="font-size:12px;">
                            <p:row>
                                <p:column colspan="#{detailMPanAnomalyQRManagedBean.colspan}" footerText="Total" />
                                <p:column style="text-align:right" footerText="#{detailMPanAnomalyQRManagedBean.valueAmtTotal}" />
                            </p:row>
                        </p:columnGroup>

                    </p:dataTable>
                    <br/><br/>

                </div>

            </h:form>
        </p:panel>

        <p:ajaxStatus onstart="PF('pleaseWaitDialog').show();" oncomplete="PF('pleaseWaitDialog').hide();" />
        <p:dialog modal="true" widgetVar="pleaseWaitDialog" showHeader="false" resizable="false" draggable="false" closable="false">
            <table border="0">
                <tr>
                    <td>
                        <h:graphicImage value="/images/preloader.gif" />
                    </td>
                    <td>
                        <h:graphicImage value="/images/spacer.gif" width="10" height="1" />
                    </td>
                    <td valign="middle">
                        <h:outputText value="Please wait ...." />
                    </td>
                </tr>
            </table>
        </p:dialog>

    </ui:define>
</ui:composition>