PRDSWEB/src/com/rintis/marketing/beans/bean/pan/PanAnomaly10M.java
package com.rintis.marketing.beans.bean.pan;

import com.rintis.marketing.beans.entity.AbstractLastUpdatedCreated;
import com.rintis.marketing.beans.entity.EsqTrxid;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.*;

/**
 * Created by aabraham on 30/01/2019.
 */
@Entity
@Table(name = "tms_trxanmly10min")
public class PanAnomaly10M extends AbstractLastUpdatedCreated {
    @Column(name = "period")
    private String period;
    @Column(name = "time_fr_10m")
    private String time_fr;
    @Column(name = "time_to_10m")
    private String time_to;
    @Column(name = "trx_type")
    private String trx_type;
    @Column(name = "tran_type")
    private String tran_type;
    @Column(name = "pan")
    private String pan;
    @Column(name = "issuer_bank")
    private String issuer_bank;
    @Column(name = "pengirim")
    private String pengirim;
    @Column(name = "freq_app")
    private Integer freq_app;
    @Column(name = "freq_dc")
    private Integer freq_dc;
    @Column(name = "freq_rvsl")
    private Integer freq_rvsl;
    @Column(name = "total_amt_app")
    private Integer total_amt_app;
    @Column(name = "total_amt_dc")
    private Integer total_amt_dc;
    @Column(name = "total_amt_rvsl")
    private Integer total_amt_rvsl;

    @OneToOne
    @JoinColumn(name="tran_type", referencedColumnName = "trx_id", insertable=false, updatable=false)
    @NotFound(action = NotFoundAction.IGNORE)
    private EsqTrxid esqTrxid;

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getTimeFr() {
        return time_fr;
    }

    public void setTimeFr(String time_fr_10m) {
        this.time_fr = time_fr_10m;
    }

    public String getTimeTo() {
        return time_to;
    }

    public void setTimeTo(String time_to_10m) {
        this.time_to = time_to_10m;
    }

    public String getTrxType() {
        return trx_type;
    }

    public void setTrxType(String trx_type) {
        this.trx_type = trx_type;
    }

    public String getTranType() {
        return tran_type;
    }

    public void setTranType(String tran_type) {
        this.tran_type = tran_type;
    }

    public String getPan() {
        return pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }

    public String getIssuerBank() {
        return issuer_bank;
    }

    public void setIssuerBank(String issuer_bank) {
        this.issuer_bank = issuer_bank;
    }

    public String getPengirim() {
        return pengirim;
    }

    public void setPengirim(String pengirim) {
        this.pengirim = pengirim;
    }

    public Integer getFreqApp() {
        return freq_app;
    }

    public void setFreqApp(Integer freq_app) {
        this.freq_app = freq_app;
    }

    public Integer getFreqDc() {
        return freq_dc;
    }

    public void setFreqDc(Integer freq_dc) {
        this.freq_dc = freq_dc;
    }

    public Integer getFreqRvsl() {
        return freq_rvsl;
    }

    public void setFreqRvsl(Integer freq_rvsl) {
        this.freq_rvsl = freq_rvsl;
    }

    public Integer getAmtApp() {
        return total_amt_app;
    }

    public void setAmtApp(Integer total_amt_app) {
        this.total_amt_app = total_amt_app;
    }

    public Integer getAmtDc() {
        return total_amt_dc;
    }

    public void setAmtDc(Integer total_amt_dc) {
        this.total_amt_dc = total_amt_dc;
    }

    public Integer getAmtRvsl() {
        return total_amt_rvsl;
    }

    public void setAmtRvsl(Integer total_amt_rvsl) {
        this.total_amt_rvsl = total_amt_rvsl;
    }

    public EsqTrxid getEsqTrxid() {
        return esqTrxid;
    }

    public void setEsqTrxid(EsqTrxid esqTrxid) {
        this.esqTrxid = esqTrxid;
    }
}

PRDSWEB/src/com/rintis/marketing/web/jsf/main/pan/AddPanAnomalyEmailManagedBean.java
package com.rintis.marketing.web.jsf.main.pan;

import com.rintis.marketing.beans.bean.bi.PanAnomalyEmailBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.web.common.PageConstant;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

/**
 * Created by aabraham on 01/03/2019.
 */
@ManagedBean
@ViewScoped
public class AddPanAnomalyEmailManagedBean extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private PanAnomalyEmailBean panAnomalyEmailBean;

    @Override
    @PostConstruct
    protected void initManagedBean() {
        panAnomalyEmailBean = new PanAnomalyEmailBean();
    }

    public String saveAction() {
        try {
            if (panAnomalyEmailBean.getUserEmail().length() == 0) {
                glowMessageError("Enter User Email", "");
                return "";
            }

            if (panAnomalyEmailBean.getGender().length() == 0) {
                glowMessageError("Enter Gender", "");
                return "";
            }

            if (panAnomalyEmailBean.getUserName().length() == 0) {
                glowMessageError("Enter Username", "");
                return "";
            }

            boolean chk = moduleFactory.getPanService().checkEmailUsed(panAnomalyEmailBean.getUserEmail());
            if (chk) {
                glowMessageError("User Email already exist", "");
                return "";
            }

            //start modify by erichie
            String actAlert1H = panAnomalyEmailBean.getAlert1H().toString();
            String actAlert3H = panAnomalyEmailBean.getAlert3H().toString();
            String actAlert6H = panAnomalyEmailBean.getAlert6H().toString();
            String actAlert1D = panAnomalyEmailBean.getAlert1D().toString();
            String actAlert3D = panAnomalyEmailBean.getAlert3D().toString();
            String actAlertMaxAmt = panAnomalyEmailBean.getAlertMaxAmt().toString();
            String actAlertMccVelocity = panAnomalyEmailBean.getAlertMccVelocity().toString();
            String actAlertSeqVelocity = panAnomalyEmailBean.getAlertSeqVelocity().toString();
            /*Add by aaw 02/07/2021*/
            String actAlertMpanAcq = panAnomalyEmailBean.getAlertMpanAcq().toString();
            /*End add*/

            moduleFactory.getPanService().saveEmail(panAnomalyEmailBean.getUserEmail(), panAnomalyEmailBean.getGender(), panAnomalyEmailBean.getUserName(), actAlert1H, actAlert3H, actAlert6H, actAlert1D, actAlert3D, actAlertMaxAmt, actAlertMccVelocity, actAlertSeqVelocity,
                actAlertMpanAcq);
            //end modify by erichie

            if (!isPostback()) {
                createTlog(moduleFactory);
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return PageConstant.PAGE_EMAIL_PAN_EMAIL_PAN + "?faces-redirect=true";
    }

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public PanAnomalyEmailBean getPanAnomalyEmail() {
        return panAnomalyEmailBean;
    }

    public void setPanAnomalyEmail(PanAnomalyEmailBean panAnomalyEmailBean) {
        this.panAnomalyEmailBean = panAnomalyEmailBean;
    }
}

PRDSWEB/src/com/rintis/marketing/web/jsf/main/pan/AddWhitelistPANManagedBean.java
package com.rintis.marketing.web.jsf.main.pan;

import com.rintis.marketing.beans.bean.bi.WhitelistBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.web.common.PageConstant;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

/**
 * Created by aabraham on 12/02/2019.
 */
@ManagedBean
@ViewScoped
public class AddWhitelistPANManagedBean  extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private WhitelistBean whitelistBean;

    @Override
    @PostConstruct
    protected void initManagedBean() {
        whitelistBean = new WhitelistBean();
    }

    public String saveAction() {
        try {
            if (whitelistBean.getPan().length() == 0) {
                glowMessageError("Enter PAN", "");
                return "";
            }

            if (whitelistBean.getPengirim().length() == 0) {
                whitelistBean.setPengirim(" ");
            }

            boolean chk = moduleFactory.getPanService().checkPanSenderUsed(whitelistBean.getPan().trim(), whitelistBean.getPengirim());
            if (chk) {
                glowMessageError("PAN And Sender Already Exist", "");
                return "";
            }

            /*Add validation by aaw 10/08/2021*/
            if (!isValid(whitelistBean.getPan())) {
                glowMessageError("PAN Not Valid", "PAN Can't Start With '-' ");
                return "";
            }
            /*End add*/

            String act = whitelistBean.getActive().toString();

            moduleFactory.getPanService().savePan(whitelistBean.getPan(), whitelistBean.getPengirim(), whitelistBean.getFreqApp(), whitelistBean.getFreqDc(), whitelistBean.getFreqDcFree(), whitelistBean.getFreqRvsl(), whitelistBean.getTotalAmtApp(), whitelistBean.getTotalAmtDc(), whitelistBean.getTotalAmtDcFree(), whitelistBean.getTotalAmtRvsl(), whitelistBean.getTotalAmt(), act);

            if (!isPostback()) {
                createTlog(moduleFactory);
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return PageConstant.PAGE_WHITELIST_PAN_WHITELIST_PAN + "?faces-redirect=true";
    }

    /*Add new method by aaw 10/08/2021*/
    public boolean isValid(String input) {
        boolean result = true;
        if (!"".equals(input.trim())) {
            if ((input.trim()).startsWith("-")) {
                result = false;
            }
        }

        return result;
    }
    /*End add*/

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public WhitelistBean getWhitelistPan() {
        return whitelistBean;
    }

    public void setWhitelistPan(WhitelistBean whitelistBean) {
        this.whitelistBean = whitelistBean;
    }
}

PRDSWEB/src/com/rintis/marketing/web/jsf/main/pan/DetailPanAnomalyInquiryPaymentManagedBean.java
package com.rintis.marketing.web.jsf.main.pan;

import com.rintis.marketing.beans.bean.bi.DetailPanAnomalyBean;
import com.rintis.marketing.beans.bean.bi.DetailPanAnomalyPaymentBean;
import com.rintis.marketing.core.SpringBeanConstant;
import com.rintis.marketing.core.app.main.module.ModuleFactory;
import com.rintis.marketing.core.utils.HttpUtils;
import com.rintis.marketing.web.jsf.AbstractManagedBean;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.text.DecimalFormat;
import java.util.List;

/**
 * Created by aabraham on 04/08/2021.
 */
@ManagedBean
@ViewScoped
public class DetailPanAnomalyInquiryPaymentManagedBean extends AbstractManagedBean {
    @ManagedProperty("#{" + SpringBeanConstant.SPRING_BEAN_MODULE_FACTORY + "}")
    private ModuleFactory moduleFactory;
    private List<DetailPanAnomalyPaymentBean> list;
    private String pPeriod;
    private String pTimeFr;
    private String pTimeTo;
    private String pPan;
    private String pPengirim;
    private String pIssuerBank;
    private String pTranType;
    private String pTranTypeId;
    private String pGroupId;
    private String pStatus;
    private String totalAmt;

    @Override
    @PostConstruct
    protected void initManagedBean() {
        try {
            //190926 Modify by AAH encode param
            pPeriod = paramEncode(getRequestParameterMap().get("pPeriod").toString());
            pTimeFr = paramEncode(getRequestParameterMap().get("pTimeFr").toString().replace(":", ""));
            pTimeTo = paramEncode(getRequestParameterMap().get("pTimeTo").toString().replace(":", ""));
            pPan = paramEncode(getRequestParameterMap().get("pPan").toString());
            pPengirim = paramEncode(getRequestParameterMap().get("pPengirim").toString());
            pIssuerBank = paramEncode(getRequestParameterMap().get("pIssuerBank").toString());
            pTranType = paramEncode(getRequestParameterMap().get("pTranType").toString());
            pStatus = paramEncode(getRequestParameterMap().get("pStatus").toString());
            pGroupId = moduleFactory.getPanService().getGroupIdFromTrxName(pTranType);
            pTranTypeId = moduleFactory.getPanService().getTrxIdFromTrxName(pTranType);

            if (!isPostback()) {
                createTlog(moduleFactory);
            }
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
    }

    public String submitAction() {
        try {
            System.out.println("PAN Anomaly Inquiry Detail - " + getUserInfoBean().getUserId() + " - PGW - " +pPeriod + " - " + pTimeFr + " - " + pTimeTo + " - " + pPan + " - " + pTranTypeId);
            list = moduleFactory.getPanService().listDetailPgw(pPeriod, pTimeFr, pTimeTo, pPan, pTranTypeId, pPengirim);
        } catch (Exception e) {
            log.error(e.getMessage(), e);
        }
        return "";
    }

    public String paramEncode(String data){
        //encrypt param
        if(!data.equals(null)){
            data = HttpUtils.encodeUrlParam(data, getUserInfoBean().getUserId(), getHttpSession().getId());
        }
        return data;
    }

    public String getValueAmtTotal() {
        Double totAmt = 0.00;

        if(list != null){
            for(DetailPanAnomalyPaymentBean l : list) {
                totAmt += Double.parseDouble(l.getAmount().toString());
            }
        }

        DecimalFormat formatter = new DecimalFormat("###,###,###.00");
        totalAmt = formatter.format(totAmt);

        return totalAmt;
    }

    public ModuleFactory getModuleFactory() {
        return moduleFactory;
    }

    public void setModuleFactory(ModuleFactory moduleFactory) {
        this.moduleFactory = moduleFactory;
    }

    public List<DetailPanAnomalyPaymentBean> getList() {
        return list;
    }

    public void setList(List<DetailPanAnomalyPaymentBean> list) {
        this.list = list;
    }

    public String getpPeriod() {
        return pPeriod;
    }

    public void setpPeriod(String pPeriod) {
        this.pPeriod = pPeriod;
    }

    public String getpTimeFr() {
        return pTimeFr;
    }

    public void setpTimeFr(String pTimeFr) {
        this.pTimeFr = pTimeFr;
    }

    public String getpTimeTo() {
        return pTimeTo;
    }

    public void setpTimeTo(String pTimeTo) {
        this.pTimeTo = pTimeTo;
    }

    public String getpPan() {
        return pPan;
    }

    public void setpPan(String pPan) {
        this.pPan = pPan;
    }

    public String getpPengirim() {
        return pPengirim;
    }

    public void setpPengirim(String pPengirim) {
        this.pPengirim = pPengirim;
    }

    public String getpIssuerBank() {
        return pIssuerBank;
    }

    public void setpIssuerBank(String pIssuerBank) {
        this.pIssuerBank = pIssuerBank;
    }

    public String getpTranType() {
        return pTranType;
    }

    public void setpTranType(String pTranType) {
        this.pTranType = pTranType;
    }

    public String getpTranTypeId() {
        return pTranTypeId;
    }

    public void setpTranTypeId(String pTranTypeId) {
        this.pTranTypeId = pTranTypeId;
    }

    public String getpGroupId() {
        return pGroupId;
    }

    public void setpGroupId(String pGroupId) {
        this.pGroupId = pGroupId;
    }

    public String getpStatus() {
        return pStatus;
    }

    public void setpStatus(String pStatus) {
        this.pStatus = pStatus;
    }
}

PRDSWEB/web/apps/pan/addWhitelistBeneficiary.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="../common/template/private_template.xhtml">
    <ui:define name="content">

        <p:panel header="#{msg.add_menu_whitelist_bene_title}" styleClass="panelContent" >
            <h:form id="frm1" >
                <p:growl id="growl" showDetail="true" escape="false" for="glowmsg" sticky="true" life="2000" />

                <div class="divPanelForm">
                    <table>
                        <tr>
                            <td valign="top">
                                <h:panelGrid columnClasses="panelGridFirstColumn, panelGridSecondColumn" columns="2" border="0" cellpadding="2" cellspacing="0">
                                    <h:outputLabel>#{msg.account_no}</h:outputLabel>

                                    <p:inputText autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.account}" size="30" maxlength="40" onkeyup="this.value=this.value.replace(/[^\d-]/,'')" />

                                    <h:outputLabel>#{msg.receiver}</h:outputLabel>
                                    <p:inputText autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.penerima}" size="30" maxlength="70" />

                                    <h:outputLabel>Frequency Approve</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.freqApp}" size="30" maxlength="8" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Decline Charge</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.freqDc}" size="30" maxlength="8" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Decline Free</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.freqDcFree}" size="30" maxlength="8" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Reversal</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.freqRvsl}" size="30" maxlength="8" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Approve</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.totalAmtApp}" size="30" maxlength="20" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Decline Charge</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.totalAmtDc}" size="30" maxlength="20" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Decline Free</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.totalAmtDcFree}" size="30" maxlength="20" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Reversal</h:outputLabel>
                                    <p:inputNumber autocomplete="off" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.totalAmtRvsl}" size="30" maxlength="20" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <ui:remove>
                                    <h:outputLabel>Amount Total</h:outputLabel>
                                    <p:inputNumber value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.totalAmt}" size="30" maxlength="20" padControl="false "  />
                                    </ui:remove>

                                    <h:outputLabel />
                                    <p:selectBooleanCheckbox itemLabel="Active" value="#{addWhitelistBeneficiaryManagedBean.whitelistBeneficiaryBean.active}" />

                                    <h:outputLabel />
                                    <h:panelGroup>
                                        <p:commandButton value="#{msg.button_save}" icon="ui-icon-disk" action="#{addWhitelistBeneficiaryManagedBean.saveAction}" update="frm1" />
                                        <h:graphicImage value="/images/spacer.gif" width="10" height="1" />
                                        <p:commandButton value="#{msg.button_cancel}" icon="ui-icon-cancel" action="listWhitelistBeneficiary.do?faces-redirect=true" immediate="true" />
                                    </h:panelGroup>

                                </h:panelGrid>
                            </td>
                        </tr>
                    </table>
                </div>

            </h:form>
        </p:panel>
    </ui:define>
</ui:composition>

PRDSWEB/web/apps/pan/editWhitelistPAN.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="../common/template/private_template.xhtml">
    <ui:define name="content">

        <p:panel header="#{msg.edit_menu_whitelist_pan_title}" styleClass="panelContent" >
            <h:form id="frm1" >
                <p:growl id="growl" showDetail="true" escape="false" for="glowmsg" sticky="true" life="2000" />

                <div class="divPanelForm">
                    <table>
                        <tr>
                            <td valign="top">
                                <h:panelGrid columnClasses="panelGridFirstColumn, panelGridSecondColumn" columns="2" border="0" cellpadding="3" cellspacing="0">
                                    <h:outputLabel>#{msg.menu_pan_no}</h:outputLabel>
                                    <h:outputText style="font-weight: bold;" escape="false" value="#{editWhitelistPANManagedBean.whitelistPan.get(0).pan}" size="30" maxlength="19" required="true" />

                                    <h:outputLabel>#{msg.menu_pan_sender}</h:outputLabel>
                                    <h:outputText style="font-weight: bold;" escape="false" value="#{editWhitelistPANManagedBean.whitelistPan.get(0).pengirim}" size="30" maxlength="70" required="true"/>

                                    <h:outputLabel>Frequency Approve</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).freqApp}" size="30" maxlength="8" padControl="false " autocomplete="false" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Decline Charge</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).freqDc}" size="30" maxlength="8" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Decline Free</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).freqDcFree}" size="30" maxlength="8" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Frequency Reversal</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).freqRvsl}" size="30" maxlength="8" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Approve</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).totalAmtApp}" size="30" maxlength="20" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Decline Charge</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).totalAmtDc}" size="30" maxlength="20" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Decline Free</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).totalAmtDcFree}" size="30" maxlength="20" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <h:outputLabel>Amount Reversal</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).totalAmtRvsl}" size="30" maxlength="20" padControl="false " autocomplete="off" minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />

                                    <ui:remove>
                                    <h:outputLabel>Amount Total</h:outputLabel>
                                    <p:inputNumber value="#{editWhitelistPANManagedBean.whitelistPan.get(0).totalAmt}" size="30" maxlength="20" padControl="false " minValue="0" onkeydown="if(event.key==='.'){event.preventDefault();}" />
                                    </ui:remove>

                                    <h:outputLabel />
                                    <p:selectBooleanCheckbox itemLabel="Active" value="#{editWhitelistPANManagedBean.whitelistPan.get(0).active}" />

                                    <h:outputLabel />
                                    <h:panelGroup>
                                        <p:commandButton value="#{msg.button_save}" icon="ui-icon-disk" action="#{editWhitelistPANManagedBean.editAction}" update="frm1" />
                                        <h:graphicImage value="/images/spacer.gif" width="10" height="1" />
                                        <p:commandButton value="#{msg.button_cancel}" icon="ui-icon-cancel" action="listWhitelistPAN.do?faces-redirect=true" immediate="true" />
                                    </h:panelGroup>

                                </h:panelGrid>
                            </td>
                        </tr>
                    </table>
                </div>

            </h:form>
        </p:panel>
    </ui:define>
</ui:composition>